### ISSUE TITLE
My City is not extracted

### ISSUE THREAD

**Issue by mholeys** [mholeys/roadtrip-choroq-tools#3]
Currently the buildings for My City, located in F023 are not extracted.

"So how does My City work? All the textures for the buildings are in the folder, but none of the buildings themselves are there."

_Originally posted by @Facepalm38 in https://github.com/mholeys/roadtrip-choroq-tools/issues/1#issuecomment-2241828792_

**Comment by mholeys** [comment]
The My City meshes are probably located within the F023, checking the coverage of the file, has showed that most of the 4th offset is being missed. This is probably where the obejcts are stored, so that they can be dynamically be loaded once the player unlocks the building. 
There is also probably blank tiles, for showing just the ground, as these are also missing in the current extraction, and would probably have to be removed when a building is placed.

**Comment by Facepalm38** [comment]
I will note that the exporter does read and export some extras. Namely, it reads and exports the Peach statue, the Start/Finish flag from the Rally and some oval-shaped model that I can only presume are the trees from the small rock that spawns with Which-Way.

All necessary textures seem to already be exported as well.

**Comment by mholeys** [comment]
So it turns out the 023.BIN has more course/field style meshes after the main 3 parts of the file, I have only been looking for car related meshes as they are simpler but were common in other files. 

After checking for field format ones, I think I have extracted all My City files, this was not a priority before. I am currently just checking for other missed parts in other fields/courses/actions.

@Facepalm38 In regards to the extra objects, I am not sure what these are for, I would doubt that they are for the actions such as Which-Way, but they could be to do with rewards/collectables. As far as I have seen, the action file contains everything needed, each file seems to only hold its own objects Otherwise the game would have to find each of these and load the whole file, just for a small piece.

**Comment by Facepalm38** [comment]
The statue shows up after completing My City and doing all My City related activities (Endurance Race, Minigames, etc.)
Start/Finish is from the Rally event you can sign up for once all mainland cities are unlocked.

The round thing I'm unsure on what it is, but I have a hunch. For the time being, it's time to re-extract everything!

Also, I see that you updated the tool with "HG3 Fixes" listed in. Is the tool now supporting HG3 models?

**Comment by mholeys** [comment]
I have not pushed the changes yet, for the new fields. However I did do some work towards HG 3 last night, it should get some meshes out of the courses, it is probably missing a fair bit, and all cars are missed/not working. Towns do not work currently. But please do have a go with the HG 3 bits, and create a new issue for any mesh bits missing.  

I will close this issue once pushed.

**Comment by Facepalm38** [comment]
For what it's worth, the HG3 cars probably have a lot lot more extras to them than the HG2 cars. Maybe that's why it skips on over?

I'll give it a shot sometime soon! You're a legend!

**Comment by mholeys** [comment]
This should be fixed in https://github.com/mholeys/roadtrip-choroq-tools/commit/444fd97ff152b999a0aac4e7f308c9c87bd567bc
